# External gems
# See http://ixti.net/software/2013/01/28/using-jekyll-plugins-on-github-pages.html for making `jekyll archives` work.
gems:
  - jekyll-archives # Sorry, not GitHub pages friendly!
  - jekyll-sitemap
  - jekyll-paginate

exclude:
  - "/vendor/"


# Site settings
<!---title: <font size="25"><font face="Myriad Pro">Zhao Yi(Akimoto Yuduki)</font></font>--->
title: "Zhao Yi(Akimoto Yuduki)"

subtitle: <font size="15"><font face="segoe script">More innovation, more miracles.</font></font>
email: scchfzy@126.com
name: WasedaAkimoto
description: >
  More innovation, more miracles.
# Base URL of site (i.e. /blog). It should always start with a slash,
# and never end with a slash. Set it to a blank value if hosting at the
# root of your server.
baseurl: "/centrarium" # the subpath of your site, e.g. /blog/
url: "https://wasedaakimoto.github.io" # the base hostname & protocol for your site
cover: "/assets/header_image.jpg"
logo:  "/assets/logo.png"

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: false
highlightjs_theme: "monokai-sublime"

# Archive settings (see https://github.com/jekyll/jekyll-archives/)
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: 'archive'
  permalinks:
    category: '/category/:name/'
    tag: '/tag/:name/'

# Disqus comments
# disqus_shortname: bencentra

# Google analytics
# ga_tracking_id: "UA-XXXX-1"

# Category descriptions (for archive pages)
descriptions:
  - cat: Academics
    desc: "Some academic knowledges."

  - cat: DailyLife
    desc: "About daily life."
    
  - cat: Photography
    desc: "The paradise of photography lovers."

  - cat: Gourment
    desc: "The enjoyments of your tongue."

commentsystem:    comment.moe
# Social icons and sharing options
#
# Social settings are used in two places:
# * In the footer, as links to your personal profiles
# * After each blog post for sharing widgets
#
# Example:
#
# social:
#   - name: Twitter                         # Name of the service
#     icon: twitter                         # Font Awesome icon to use (minus fa- prefix)
#     username: "@TheBenCentra"             # (User) Name to display in the footer link
#     url: https://twitter.com/TheBenCentra # URL of your profile (leave blank to not display in footer)
#     desc: Follow me on Twitter            # Description to display as link title, etc
#     share: true                           # Include in the "Share" section of posts
social:
  - name: Twitter
    icon: twitter
    username: TheBenCentra
    url:
    desc: Follow me on Twitter
    share: false

  - name: Facebook
    icon: facebook
    username: Zhao Yi
    url: https://www.facebook.com/profile.php?id=100010808733797
    desc: Friend me on Facebook
    share: true

  - name: GitHub
    icon: github
    username: WasedaAkimoto
    url: https://github.com/WasedaAkimoto
    desc: Fork me on GitHub
    share: true

  - name: QQZone
    icon: qq
    username: 秋本明
    url: https://user.qzone.qq.com/751389748
    desc: Friend me on QQZone
    share: true

  - name: QQ
    icon: qq
    username: 秋本明
    url: 
    share: false

  - name: Weibo
    icon: qq
    username: 秋本明AkimotoAkila
    url: http://weibo.com/3592131742/profile?rightmod=1&wvr=6&mod=personinfo
    desc: Follow me on Weibo
    share: true

  - name: LinkedIn
    icon: linkedin
    username: 赵易
    url: http://www.linkedin.com/in/%E6%98%93-%E8%B5%B5-ba694986/
    desc: Connect with me on LinkedIn
    share: true

  - name: Google+
    icon: google-plus
    username:
    url:
    desc: Add me to your Circles
    share: false

  - name: YouTube
    icon: youtube
    username:
    url:
    desc: Subscribe on YouTube
    share: false

  - name: Instagram
    icon: instagram
    username: waseda_akimoto_zhao
    url: https://www.instagram.com/waseda_akimoto_zhao/
    desc: Follow me on Instagram
    share: true

  - name: Pinterest
    icon: pinterest
    username:
    url:
    desc: Follow me on Pinterest
    share: false

  - name: SoundCloud
    icon: soundcloud
    username:
    url:
    desc: Follow me on SoundCloud
    share: false

  - name: Tumblr
    icon: tumblr
    username:
    url:
    desc: Follow me on Tumblr
    share: false

  - name: Steam
    icon: steam
    username:
    url:
    desc: Friend me on Steam
    share: false

  - name: Dribbble
    icon: dribbble
    username:
    url:
    desc: Follow me on Dribble
    share: false

  - name: Vimeo
    icon: vimeo-square
    username:
    url:
    desc: Follow me on Vimeo
    share: false

  - name: Vine
    icon: vine
    username:
    url:
    desc: Follow me on Vine
    share: false

  - name: Reddit
    icon: reddit
    username:
    url:
    desc: Share to Reddit
    share: false

  - name: "Hacker News"
    icon: hacker-news
    username:
    url:
    desc: Share to Hacker News
    share: false

# Social sharing protocols
# These are for automatically generating sharing metadata for FB and Twitter
# OS Protocol is for sharing the source of your site, if you're interested. For more, see osprotocol.com
protocols:
    fb_image: "/assets/logo.png"
    fb_image_width: 612
    fb_image_height: 605
    fb_image_type: "image/png"

    twitter_image: "/assets/logo.png"

    os_repo: "https://github.com/bencentra/centrarium.com"
    os_rcs_type: "git"
    os_src: "git@github.com:bencentra/centrarium.com.git"
